OASIS3 Interface added for ParFlow via new amps option, AMPS=oas3 This option allows coupling of ParFlow with CLM3.5 Other additional updates: 1) Use of van-genuchten parameter n<2 2) Keep terrain following grid definition outside of CLM def in solver_richards.c 3) configure file updated to compile parflow with oasis 4) Mannings coef. for 2D PFB file
git-svn-id: https://parflow.svn.cloudforge.com/parflow/parflow/trunk@653 39af3fb0-ca4e-0410-adf9-b4ae76d04516

diff --git a/pftools/configure b/pftools/configure
--- a/pftools/configure
+++ b/pftools/configure
@@ -9183,6 +9183,9 @@ case "$with_amps" in
   mpi1)
     AMPS=mpi1
   ;;
+  oas3)
+    AMPS=oas3
+  ;;
   smpi)
     AMPS=smpi
   ;;
@@ -9190,8 +9193,8 @@ case "$with_amps" in
     AMPS=win32
   ;;
   *)
-    { { echo "$as_me:$LINENO: error: Invalid AMPS version specified, use seq, mpi1, smpi, win32" >&5
-echo "$as_me: error: Invalid AMPS version specified, use seq, mpi1, smpi, win32" >&2;}
+    { { echo "$as_me:$LINENO: error: Invalid AMPS version specified, use seq, mpi1, oas3, smpi, win32" >&5
+echo "$as_me: error: Invalid AMPS version specified, use seq, mpi1, oas3, smpi, win32" >&2;}
    { (exit 1); exit 1; }; }
   ;;
 esac
