Use CC compiler if -shared option is supported, otherwise default to using ld to build shared libraries; this helps bring in compiler dependent libraries
git-svn-id: https://parflow.svn.cloudforge.com/parflow/parflow/trunk@281 39af3fb0-ca4e-0410-adf9-b4ae76d04516

diff --git a/pftools/configure b/pftools/configure
--- a/pftools/configure
+++ b/pftools/configure
@@ -703,9 +703,9 @@ ac_ct_CXX
 hdf5_LIBS
 CHUNK_DIR
 PARFLOW_HAVE_CHUNK
+SED
 SHLIB_SUFFIX
 SHLIB_LD
-SED
 SHLIB_CFLAGS
 INSTDIR
 M4
@@ -10007,22 +10007,6 @@ fi
 
 INSTDIR=$prefix
 
-# SGS This could be done better but just test on OS for now
-case "$host_os" in
-  darwin*)
-    SHLIB_SUFFIX=".dylib"
-    SHLIB_LD="ld -dylib"
-    ;;
-  *)
-    SHLIB_SUFFIX=".so"
-    SHLIB_LD="ld -shared"
-    ;;
-esac
-
-
-
-
-
 { echo "$as_me:$LINENO: checking for a sed that does not truncate output" >&5
 echo $ECHO_N "checking for a sed that does not truncate output... $ECHO_C" >&6; }
 if test "${ac_cv_path_SED+set}" = set; then
@@ -10106,6 +10090,126 @@ fi
 echo "${ECHO_T}$ac_cv_path_SED" >&6; }
  SED="$ac_cv_path_SED"
   rm -f conftest.sed
+
+
+
+
+
+
+  flag=`echo "-shared" | $SED 'y% .=/+-(){}<>:*,%_______________%'`
+
+  { echo "$as_me:$LINENO: checking whether the C compiler accepts the -shared flag" >&5
+echo $ECHO_N "checking whether the C compiler accepts the -shared flag... $ECHO_C" >&6; }
+if { as_var=ax_cv_c_check_flag_$flag; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+
+    ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+    save_CFLAGS="$CFLAGS"
+    CFLAGS="$CFLAGS -shared"
+    cat >conftest.$ac_ext <<_ACEOF
+
+      /* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+
+      eval "ax_cv_c_check_flag_$flag=yes"
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+      eval "ax_cv_c_check_flag_$flag=no"
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+
+    CFLAGS="$save_CFLAGS"
+
+    ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+
+fi
+ac_res=`eval echo '${'ax_cv_c_check_flag_$flag'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+
+  if eval "test \"`echo '$ax_cv_c_check_flag_'$flag`\" = yes"; then
+
+    :
+    CC_HAS_SHARED="yes";CC_SHARED_FLAG="-shared"
+
+else
+
+    :
+    CC_HAS_SHARED="no";CC_SHARED_FLAC=""
+
+fi
+
+
+
+# SGS This could be done better but just test on OS for now
+case "$host_os" in
+  darwin*)
+    SHLIB_SUFFIX=".dylib"
+    SHLIB_LD="ld -dylib"
+    ;;
+  *)
+    SHLIB_SUFFIX=".so"
+    if test "$CC_HAS_SHARED" = "yes"; then
+        SHLIB_LD="$CC -shared"
+    else
+        SHLIB_LD="ld -shared"
+    fi
+    ;;
+esac
+
+
+
+
 
 
 
@@ -10979,9 +11083,9 @@ ac_ct_CXX!$ac_ct_CXX$ac_delim
 hdf5_LIBS!$hdf5_LIBS$ac_delim
 CHUNK_DIR!$CHUNK_DIR$ac_delim
 PARFLOW_HAVE_CHUNK!$PARFLOW_HAVE_CHUNK$ac_delim
+SED!$SED$ac_delim
 SHLIB_SUFFIX!$SHLIB_SUFFIX$ac_delim
 SHLIB_LD!$SHLIB_LD$ac_delim
-SED!$SED$ac_delim
 SHLIB_CFLAGS!$SHLIB_CFLAGS$ac_delim
 INSTDIR!$INSTDIR$ac_delim
 M4!$M4$ac_delim
